-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- touchpad speed

hl.device({
    name = "elan0791:00-04f3:30fd-touchpad",
    sensitivity = 0.1,
})

hl.device({
    name = "logitech-g203-lightsync-gaming-mouse",
    sensitivity = -0.7,
})

hl.device({
    name = "hanvon-ugee-6-inch-pentablet-pen",
    sensitivity = 1,
    accel_profile = "flat",
    active_area_size = "80 50",
    active_area_position = "0 0",
})
