-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- --- Cursori ---

hl.env("HYPRCURSOR_THEME", "Notwaita-Black")

hl.env("HYPRCURSOR_SIZE", 24)

hl.env("XCURSOR_THEME", "Notwaita-Black")

hl.env("XCURSOR_SIZE", 24)

-- --- Backend e Toolkit ---

hl.env("GDK_BACKEND", "wayland,x11")

hl.env("QT_QPA_PLATFORM", "wayland;xcb")

hl.env("SDL_VIDEODRIVER", "wayland")

hl.env("CLUTTER_BACKEND", "wayland")

-- --- XDG Specifications ---

hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

hl.env("XDG_SESSION_TYPE", "wayland")

hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- --- Qt Variables ---

hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", 1)

hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", 1)

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")

-- --- Temi ---

hl.env("GTK_THEME", "Tokyonight-Dark-B")

-- --- Ottimizzazioni Extra ---

hl.env("MOZ_ENABLE_WAYLAND", 1)

hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
