-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

hl.config({
	input = {
		kb_options = "caps:swapescape",
		follow_mouse = 1,
		touchpad = {
			natural_scroll = true,
		},
		--		move_focuses_monitor = false,
	},
})
